### ISSUE TITLE
Issue in UC-t11 code

### ISSUE THREAD

**Issue by salmansaeed90** [Milesight-IoT/SensorDecoders#2]
Dears

I am trying the decoder function but in response, I am getting below error packet:

Error:”js vm error: ReferenceError: ‘Decode’ is not defined”,

Also I have noted that the sensor is not sending Battery information in the packet.

See the below packet details:

Payload(hex): 0167100102683f

**Comment by gfnord** [comment]
Hi, are you using chirpstack or the things network Lora stack?

**Comment by gfnord** [comment]
Probably you're using chirpstack, since it is calling a decoder function called "Decode", but you copied the js for TTN, in which the function is called 'Decoder', and that's why the js vm doesn't find the Decode function.

Please try the https://github.com/Milesight-IoT/SensorDecoders/blob/master/UC11-T1/UC11-T1_Chirpstack.js decoder script.
